### PR TITLE
Add hasNoText assertion

### LINKED ISSUE #356: Add `hasNoText()` assertion
this would essentially be an alias for `hasText('')` with custom assertions messages

### PR DESCRIPTION
**Pull request by step2yeung**
Copy of #382 to resolve #356

### CODE REVIEW

**Comment by scalvert** [comment]
You have a prettier error :)

**Comment by step2yeung** [comment]
@scalvert it's pretty again

**Comment by scalvert** [comment]
@step2yeung can you rebase this change and re-run `yarn docs`? :)

**Comment by step2yeung** [comment]
@scalvert rebased and re-`yarn docs`

**Pull request merged**
