### PR TITLE
Add includesText() alias

### LINKED ISSUE #30: Add includesText() alias
... for `hasTextContaining()`

### PR DESCRIPTION
**Pull request by Oreoz**
Fixes #30.

I did not find tests for other aliases, therefore I didn't write any for this one.

I edited the API.md file manually (EditorConfig had some fun) in order to add mention of the alias. I wasn't sure if it was generated or maintained manually.

### CODE REVIEW

**Comment by Turbo87** [comment]
> I edited the API.md file manually (EditorConfig had some fun) in order to add mention of the alias. I wasn't sure if it was generated or maintained manually.

you can `yarn run docs` and it will automatically generate the `API.md` file :)

**Comment by Oreoz** [comment]
There you go! Generated the docs using `yarn run docs`.

I also took the liberty of adding a minuscule 'Contributing' section in the README to cover stuff I tripped up on. I hope that's alright with you.

**Comment by Turbo87** [comment]
awesome, thanks!!

**Comment by Turbo87** [comment]
if you want to continue working on this I was thinking that maybe another alias `containsText()` might also be good, and then we should probably make `includesText()` the main implementation (due to `String.prototype.includes()`) and `hasTextContaining()` an alias to `includesText()`.

**Comment by Oreoz** [comment]
Sure thing, if I have some spare time today, I'll look into that!

**Pull request merged**
