### PR TITLE
Add hasNoText assertion

### PR DESCRIPTION
**Pull request by step2yeung**
For #356

### CODE REVIEW

**Comment by scalvert** [comment]
@step2yeung care to fix the merge conflict with the API.md file? You'll likely need to rebase with master and regenerate it using `yarn docs`.

**Comment by scalvert** [comment]
Not sure why this closed. I didn't close it...

**Comment by scalvert** [comment]
@Turbo87 can you reopen?

**Comment by step2yeung** [comment]
Uhh.. weird.. the commit with the changes got overwritten by the latest force-push

**Comment by scalvert** [comment]
Derp. Did I nuke them? Do you have them in your reflog?

**Comment by scalvert** [comment]
You're allowed to kick me when I'm next in the office...

**Pull request closed without merging**
